---
version: '3'
services:
  backend:
    image: venkynagidi/backend:latest
    ports:
      - "3000:3000"
    networks:
      - backend-network
      - frontend-network
   
  
  frontend:
    image: venkynagidi/frontend:latest
    ports:
      - "8085:80"
    networks:
      - frontend-network
      - backend-network
   
      
networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
