---
version: '3.8'
services:
  backend:
    image: venkynagidi/backend:latest
    environment:
      - PORT=3001
    deploy:
      replicas: 4
    networks:
      - loadbalancing
   
  
  frontend:
    image: venkynagidi/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - loadbalancing
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
   volumes:
     - " .nginx.conf /etc/nginx/conf.d"

     
      
networks:
  loadbalancing:
