---
version: '3'
services:
  backend:
    image: venkynagidi/backend:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 4
    networks:
      - loadbalancing
   
  
  frontend:
    image: venkynagidi/frontend:latest
    ports:
      - "8085:80"
    networks:
      - loadbalancing
    depends_on:
      - backend
   
      
networks:
  loadbalancing:
