---
version: '3.8'
services:
  backend:
    image: venkynagidi/backend:latest
    environment:
      - PORT=3000
    deploy:
      replicas: 3
    networks:
      - loadbalancing
   
  
  frontend:
    image: venkynagidi/frontend:latest
    ports:
      - "8085:80"
    networks:
      - loadbalancing
    depends_on:
      - backend
   
      
networks:
  loadbalancing:
