version: '3.8'

services:
  frontend:
    image: venkynagidi/frontendimage:one
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend-network
      - backend-network

  backend:
    image: venkynagidi/backendimage:one
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend-network
      - frontend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
