---
version: '3.8'
services:
  backend:
    image: venkynagidi/backend:latest
    environment:
      - PORT=3000
    deploy:
      replicas: 4
    networks:
      - "loadbalancing"
   
  
  frontend:
    image: venkynagidi/frontend:latest
    ports:
      - "8089:80"
    networks:
      - "loadbalancing"
    depends_on:
      - backend
  
  
networks:
  loadbalancing:
    driver: bridge
